replicaCount: 3
image:
  repository: vinhbh/vdt_api
  pullPolicy: IfNotPresent
  tag: "v2.7"
  
service:
  type: NodePort
  port: 8000
  nodePort: 30002

database:
  host: vdt-db-postgres-chart
  port: 5432
  name: vdt_db
  user: vinhbh
  password: "123456789"

resources: {}
